name: Preview Terraform Plan

on:
  pull_request:

jobs:
  preview:
    name: Plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      ### Install tooling

      - name: Install Terramate
        uses: terramate-io/terramate-action@b5d1461d435ba454179045ea062bbecb32738913 # v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3

      - name: Install Terraform with asdf
        run: |
          asdf plugin add terraform
          asdf install terraform

      - name: List changed stacks
        id: list
        run: |
          echo "stdout<<STDOUT" >>$GITHUB_OUTPUT
          terramate list --changed >>$GITHUB_OUTPUT
          EXIT_CODE=$?
          echo "STDOUT" >>$GITHUB_OUTPUT
          exit ${EXIT_CODE}

      - name: Configure AWS Credentials
        if: steps.list.outputs.stdout
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: eu-west-1

          # This IAM role has been created in "bootstrap/demo"
          role-to-assume: "arn:aws:iam::835367859851:role/terraform-20240607091057657900000001"
          role-session-name: TerramatePlan

      - name: Create Terraform plan on changed stacks
        if: steps.list.outputs.stdout
        run: |
          terramate run --changed -- terraform init
          terramate run --changed -- terraform validate
          terramate run --changed -- terraform plan -out out.tfplan

      - name: Generate Preview Comment
        if: steps.list.outputs.stdout
        id: comment
        run: |
          echo >>pr-comment.txt "### List of Changed Stacks"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```bash'
          echo >>pr-comment.txt "${{ steps.list.outputs.stdout }}"
          echo >>pr-comment.txt '```'
          echo >>pr-comment.txt
          echo >>pr-comment.txt "#### Terraform Plan"
          echo >>pr-comment.txt
          echo >>pr-comment.txt '```terraform'
          terramate run --changed -- terraform show -no-color out.tfplan 2>&1 | dd bs=1024 count=248 >>pr-comment.txt
          echo >>pr-comment.txt '```'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Inform about no Changed Stacks
        if: (!steps.list.outputs.stdout)
        run: |
          echo >>pr-comment.txt '### No changed stacks.'
          cat pr-comment.txt >>$GITHUB_STEP_SUMMARY

      - name: Publish Plans for Changed Stacks
        uses: marocchino/sticky-pull-request-comment@331f8f5b4215f0445d3c07b4967662a32a2d3e31 # v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: terraform-plan
          path: pr-comment.txt
